/**
 * ExileClient_system_scavenge_initialize
 *
 */
 
ExileClient_gui_holdActionAdd = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_gui_holdActionAdd.sqf";
ExileClient_system_scavenge_getItemComponents = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_system_scavenge_getItemComponents.sqf";
ExileClient_system_scavenge_checkItemConditions = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_system_scavenge_checkItemConditions.sqf";
ExileClient_system_scavenge_action_craftItem = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_system_scavenge_action_craftItem.sqf";
ExileClient_system_scavenge_action_conditionEvents = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_system_scavenge_action_conditionEvents.sqf";
ExileClient_system_scavenge_createLoot = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_system_scavenge_createLoot.sqf";
ExileClient_object_player_scavenge_addAction = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_object_player_scavenge_addAction.sqf";
[] call ExileClient_system_scavenge_getItemComponents;
[] call ExileClient_object_player_scavenge_AddAction;