/**
 * ExileClient_system_scavenge_initialize
 *
 */
 
ExileClient_gui_holdActionAdd = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_gui_holdActionAdd.sqf";
ExileClient_system_scavenge_getCraftingRecipes = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_system_scavenge_getCraftingRecipes.sqf";
ExileClient_system_scavenge_checkCraftConditions = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_system_scavenge_checkCraftConditions.sqf";
ExileClient_system_scavenge_action_craftItem = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_system_scavenge_action_craftItem.sqf";
ExileClient_system_scavenge_action_conditionEvents = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_system_scavenge_action_conditionEvents.sqf";
ExileClient_system_scavenge_createLoot = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_system_scavenge_createLoot.sqf";
ExileClient_object_player_scavenge_addAction = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_object_player_scavenge_addAction.sqf";
ExileClient_object_player_playScavengeEvent = compileFinal preprocessFileLineNumbers "custom\Scavenge\ExileClient_object_player_playScavengeEvent.sqf";
[] call ExileClient_object_player_scavenge_AddAction;